version: '3'
services:
  influxdb:
    image: influxdb:2.7.6
    container_name: influxdb2
    ports:
      - "8087:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=jorgeoa
      - DOCKER_INFLUXDB_INIT_PASSWORD=24872487
      - DOCKER_INFLUXDB_INIT_ORG=aspro
      - DOCKER_INFLUXDB_INIT_BUCKET=sensores
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    networks:
      - influxdb_net

  nodered:
    build: .
    container_name: mynodered
    ports:
      - "1881:1880"
    volumes:
      - nodered-data:/data
    networks:
      - influxdb_net

  grafana:
    image: grafana/grafana
    container_name: grafana_local
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - influxdb_net

  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    networks:
      - influxdb_net

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1884:1883"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - influxdb_net

volumes:
  influxdb-data:
  influxdb-config:
  nodered-data:
  grafana-data:
  mosquitto-data:
  mosquitto-log:

networks:
  influxdb_net:

